'use strict';
const menuButton=document.querySelector('.menu-button');
const menu=document.querySelector('#menu');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));menu.classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu?.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=button.dataset.filter!=='Todas'&&card.dataset.category!==button.dataset.filter})}));
const photoDialog=document.querySelector('#photo-dialog');
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{photoDialog.querySelector('img').src=b.dataset.photo;photoDialog.querySelector('img').alt=b.dataset.caption;photoDialog.querySelector('p').textContent=b.dataset.caption;photoDialog.showModal()}));
photoDialog?.querySelector('.close-dialog').addEventListener('click',()=>photoDialog.close());
photoDialog?.addEventListener('click',e=>{if(e.target===photoDialog)photoDialog.close()});
document.querySelector('[data-share]')?.addEventListener('click',async()=>{const status=document.querySelector('#share-status');try{if(navigator.share){await navigator.share({title:document.title,url:location.href})}else if(navigator.clipboard&&location.protocol!=='file:'){await navigator.clipboard.writeText(location.href);status.textContent='Link copiado.'}else{status.textContent='Copie o endereço desta página para compartilhar.'}}catch(e){if(e.name!=='AbortError')status.textContent='Copie o endereço desta página para compartilhar.'}});
// O Pix só é mostrado quando há um payload EMV e uma imagem de QR confirmados.
if(document.querySelector('#pix-area'))fetch('conteudo.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{const pix=data.pix;if(!pix?.payload?.startsWith('000201')||!pix.favorecido||!pix.qr_image)return;const box=document.querySelector('#pix-area');box.replaceChildren();const image=document.createElement('img');image.src=pix.qr_image;image.alt='QR Code Pix para apoiar o grupo';const recipient=document.createElement('p');recipient.textContent='Favorecido: '+pix.favorecido;const button=document.createElement('button');button.className='button orange';button.textContent='Copiar código Pix';const status=document.createElement('p');status.setAttribute('role','status');button.onclick=async()=>{try{await navigator.clipboard.writeText(pix.payload);status.textContent='Código copiado. Confira o favorecido no aplicativo do seu banco.'}catch{const field=document.createElement('textarea');field.value=pix.payload;field.readOnly=true;field.setAttribute('aria-label','Código Pix para copiar');box.append(field);field.select();status.textContent='Selecione e copie o código acima.'}};box.append(image,recipient,button,status)}).catch(()=>{});
